version: "3"

services:
  dev-database:
    image: library/mysql:5.7
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
      MYSQL_DATABASE: 'demo'
  testrunner:
    image: testrunner
    depends_on:
      - dev-database
    environment:
      DB: dev-database # note hostname is defined by service name above.

